language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
# Modules nécessaire pour le mode auteur (Build update)
before_install: cpanm --notest LWP::UserAgent HTTP::Date File::Copy File::Spec Spreadsheet::ParseExcel Regexp::Assemble::Compressed Template
script: "perl Build.PL && { ./Build update || perl Build.PL ; } && ./Build test"
