language: perl
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
sudo: false
# Modules nécessaire pour le mode auteur (Build update)
# TODO utiliser "./Build installdeps" car on l'a surchargé pour les
#      dépendances auteur
install:
    # Regexp::Assemble 0.35 has POD tests failing
    - cpanm --notest Regexp::Assemble
    - cpanm --notest LWP::UserAgent HTTP::Date File::Copy File::Spec Spreadsheet::ParseExcel Regexp::Assemble::Compressed Template Test::Pod Test::Pod::Coverage Test::MinimumVersion Regexp::Parser experimental
    # Test::Kwalitee indépendant car il est long à installer et Travis-CI
    # limite le temps d'exécution d'une commande à 15 mn
    - cpanm --notest Test::Kwalitee
    - cpanm Number::Phone
script:
    - perl Build.PL
    - ./Build manifest
    - ./Build update
    - perl Build.PL
    - ./Build manifest
    - ./Build distmeta
    - AUTHOR_TESTING=1 RELEASE_TESTING=1 ./Build disttest
